dcConsData = [
	{name:"4달라.png", keywords:["4달라", "4딸라", "사딸라"], tags:["4달라"]},
	{name:"네다씹.jpg", keywords:["네다씹", "네다십", "네다쉽"], tags:["네다씹"]},
	{name:"흑염룡.jpg", keywords:["흑염룡", "중2병"], tags:["흑염룡"]},
	{name:"가능.png", keywords:["가능"], tags:["가능"]},
	{name:"둘리처신.png", keywords:["처신", "둘리처신"], tags:["둘리"]},
	{name:"마참내.png", keywords:["마참내", "마침내"], tags:["마참내"]},
	{name:"민초.gif", keywords:["민초"], tags:["민초"]},
	{name:"불편.png", keywords:["불편"], tags:["불편"]},
	{name:"싸닉.png", keywords:["싸닉"], tags:["싸닉"]},

	{name:"둘리어서.png", keywords:["둘리어서"], tags:["둘리"]},
	{name:"둘리꼴.png", keywords:["둘리꼴"], tags:["둘리"]},
	{name:"둘리선.png", keywords:["둘리선"], tags:["둘리"]},
	{name:"놀랍다.gif", keywords:["놀랍다"], tags:["놀랍다"]},
	{name:"펀쿨.png", keywords:["펀쿨"], tags:["펀쿨"]},
	{name:"라인따봉.png", keywords:["라인따봉"], tags:["라인"]},

	{name:"우리핵박수1.gif", keywords:["우리핵박수1"], tags:["우리핵"]},
	{name:"우리핵박수2.gif", keywords:["우리핵박수2"], tags:["우리핵"]},
	{name:"우리핵박수3.gif", keywords:["우리핵박수3"], tags:["우리핵"]},
	{name:"우리핵아닌데.gif", keywords:["우리핵아닌데"], tags:["우리핵"]},
	{name:"우리핵안녕.gif", keywords:["우리핵안녕"], tags:["우리핵"]},
	{name:"즐겁다.png", keywords:["즐겁다"], tags:["즐겁다"]},
	{name:"펀쿨끄덕.gif", keywords:["펀쿨끄덕"], tags:["펀쿨끄덕"]},
	{name:"펄럭.gif", keywords:["펄럭"], tags:["펄럭"]},
	{name:"편안.png", keywords:["편안"], tags:["편안"]},
	{name:"혼란앵무.gif", keywords:["혼란앵무"], tags:["혼란앵무"]},
	{name:"제리감사.gif", keywords:["제리감사"], tags:["제리감사"]},
	{name:"톰감사.gif", keywords:["톰감사"], tags:["톰감사"]},
	{name:"폭발.gif", keywords:["폭발"], tags:["폭발"]},
	{name:"인공지능.jpg", keywords:["인공지능"], tags:["인공지능"]},
	{name:"콜라.jpg", keywords:["콜라"], tags:["콜라"]},
	{name:"흠.png", keywords:["흠"], tags:["흠"]}
];